from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/exploration_editor/statistics_tab/issues_directive.html'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'<div class="oppia-issues-issue-dir">\n  <div class="row oppia-issues-content oppia-issues-row-eq-height">\n    <div class="col-md-2 oppia-issues-border-gray oppia-ft-14">\n      <div ng-repeat="issue in issues" class="row">\n        <div ng-if="isIssueOnInitDisplay()" class="issueNav text-center col-md oppia-issues-bor-btm oppia-issues-clr-green oppia-pt2 oppia-pb2 oppia-issues-bg-clr oppia-issues-text-white protractor-test-issue<[getIssueIndex(issue)]>" ng-click="makeVisible(getIssueIndex(issue))" id="issueNav<[getIssueIndex(issue)]>">\n          Issue <[createIssueNavId(issue)]>\n        </div>\n        <div ng-if="!isIssueOnInitDisplay()" class="issueNav text-center col-md oppia-issues-bor-btm oppia-issues-clr-green oppia-pt2 oppia-pb2 protractor-test-issue<[getIssueIndex(issue)]>" ng-click="makeVisible(getIssueIndex(issue))" id="issueNav<[getIssueIndex(issue)]>">\n          Issue <[createIssueNavId(issue)]>\n        </div>\n      </div>\n    </div>\n    <div class="col-md-9 oppia-issues-border-gray">\n      <div ng-repeat="issue in issues">\n        <div ng-if="isIssueOnInitDisplay()" style="display: block;" id="issue<[getIssueIndex(issue)]>">\n          <div ng-if="issue.issueType == \'EarlyQuit\'">\n            <early-quit-issue-directive index="getIssueIndex(issue)" issue="issue"/>\n          </div>\n          <div ng-if="issue.issueType == \'MultipleIncorrectSubmissions\'">\n            <multiple-incorrect-issue-directive index="getIssueIndex(issue)" issue="issue"/>\n          </div>\n          <div ng-if="issue.issueType == \'CyclicStateTransitions\'">\n            <cyclic-transitions-issue-directive index="getIssueIndex(issue)" issue="issue"/>\n          </div>\n        </div>\n        <div ng-if="!isIssueOnInitDisplay()" style="display: none;" id="issue<[getIssueIndex(issue)]>">\n          <div ng-if="issue.issueType == \'EarlyQuit\'">\n            <early-quit-issue-directive index="getIssueIndex(issue)" issue="issue"/>\n          </div>\n          <div ng-if="issue.issueType == \'MultipleIncorrectSubmissions\'">\n            <multiple-incorrect-issue-directive index="getIssueIndex(issue)" issue="issue"/>\n          </div>\n          <div ng-if="issue.issueType == \'CyclicStateTransitions\'">\n            <cyclic-transitions-issue-directive index="getIssueIndex(issue)" issue="issue"/>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>'

blocks = {}
debug_info = ''