from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/exploration_editor/exploration_metadata_modal_directive.html'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'<div class="modal-header">\n  <h3>Add Some Details</h3>\n</div>\n\n<div class="modal-body oppia-long-text">\n  <p>\n    Just a few more things before you publish:\n  </p>\n  <exploration-title-editor ng-if="requireTitleToBeSpecified"\n                            label-text="Add a title: what should your exploration be called?"\n                            form-style="{\'font-weight\':\'normal\'}">\n  </exploration-title-editor>\n  <exploration-objective-editor ng-if="requireObjectiveToBeSpecified"\n                                label-text="Add a goal: what does the exploration help people to do?"\n                                form-style="{\'font-weight\': \'normal\'}">\n  </exploration-objective-editor>\n  <p ng-if="requireCategoryToBeSpecified">\n    Add a category: how would you categorize your exploration?\n    <select2-dropdown item="explorationCategoryService.displayed"\n                      choices="CATEGORY_LIST_FOR_SELECT2"\n                      placeholder="Choose or type new"\n                      new-choice-regex="^[A-Z a-z]+$"\n                      width="100%"\n                      invalid-search-term-message="Invalid category name">\n    </select2-dropdown>\n  </p>\n\n  <p ng-if="askForLanguageCheck">\n    Verify the language: is your exploration written in this language?\n    <select id="explorationLanguageCode" class="form-control protractor-test-exploration-language-select" ng-model="explorationLanguageCodeService.displayed" ng-change="saveExplorationLanguageCode()" ng-options="lc.code as lc.description for lc in explorationLanguageCodeService.getAllLanguageCodes()">\n    </select>\n  </p>\n  <p ng-if="askForTags">\n    Add tags to help learners discover your exploration.\n    <select2-dropdown item="explorationTagsService.displayed"\n                      choices="explorationTagsService.displayed"\n                      allow-multiple-choices="true"\n                      invalid-search-term-message="Add a new tag (using lowercase letters and spaces)..."\n                      new-choice-regex="<[::TAG_REGEX]>"\n                      width="100%"\n                      placeholder="Skills, concepts, topics..."\n                      on-selection-change="saveExplorationTags()">\n    </select2-dropdown>\n  </p>\n</div>\n\n<div class="modal-footer">\n  <button class="btn btn-default" ng-click="cancel()">Cancel</button>\n  <button class="btn btn-success protractor-test-confirm-pre-publication" ng-click="save()" ng-disabled="!isSavingAllowed()">Save Changes</button>\n</div>'

blocks = {}
debug_info = ''