from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/splash/Splash.js'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'// Copyright 2014 The Oppia Authors. All Rights Reserved.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an "AS-IS" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\n/**\n * @fileoverview Data and controllers for the Oppia splash page.\n */\n\noppia.controller(\'Splash\', [\n  \'$scope\', \'$timeout\', \'$window\', \'siteAnalyticsService\',\n  \'UrlInterpolationService\',\n  function($scope, $timeout, $window, siteAnalyticsService,\n      UrlInterpolationService) {\n    $scope.userIsLoggedIn = GLOBALS.userIsLoggedIn;\n    $scope.getStaticImageUrl = UrlInterpolationService.getStaticImageUrl;\n    $scope.getStaticSubjectImageUrl = function(subjectName) {\n      return UrlInterpolationService.getStaticImageUrl(\'/subjects/\' +\n        subjectName + \'.svg\');\n    };\n\n    $scope.onRedirectToLogin = function(destinationUrl) {\n      siteAnalyticsService.registerStartLoginEvent(\n        \'splashPageCreateExplorationButton\');\n      $timeout(function() {\n        $window.location = destinationUrl;\n      }, 150);\n      return false;\n    };\n\n    $scope.onClickBrowseLibraryButton = function() {\n      siteAnalyticsService.registerClickBrowseLibraryButtonEvent();\n      $timeout(function() {\n        $window.location = \'/library\';\n      }, 150);\n      return false;\n    };\n\n    $scope.onClickCreateExplorationButton = function() {\n      siteAnalyticsService.registerClickCreateExplorationButtonEvent();\n      $timeout(function() {\n        $window.location = \'/creator_dashboard?mode=create\';\n      }, 150);\n      return false;\n    };\n  }\n]);'

blocks = {}
debug_info = ''