from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/library/LibrarySpec.js'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'// Copyright 2014 The Oppia Authors. All Rights Reserved.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an "AS-IS" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\n/**\n * @fileoverview Unit tests for the controller of the library page.\n */\n\ndescribe(\'Library controller\', function() {\n  beforeEach(module(\'oppia\'));\n\n  describe(\'Library\', function() {\n    var scope, ctrl, rootScope, $httpBackend;\n\n    beforeEach(function() {\n      module(\'ui.bootstrap\');\n    });\n\n    beforeEach(module(\'oppia\', GLOBALS.TRANSLATOR_PROVIDER_FOR_TESTS));\n\n    beforeEach(inject(function($controller, _$httpBackend_, $rootScope) {\n      $httpBackend = _$httpBackend_;\n      $httpBackend.expectGET(\'/searchhandler/data\').respond({\n        allow_yaml_file_upload: false,\n        explorations_list: [{\n          id: \'3\',\n          title: \'Geography 2\',\n          category: \'Geography\',\n          objective: \'can view more maps\',\n          language: \'espa\xf1ol\',\n          last_updated: 12345678912345,\n          community_owned: false,\n          status: \'featured\'\n        }, {\n          id: \'5\',\n          title: \'Landmarks\',\n          category: \'Geography\',\n          objective: \'can view maps\',\n          language: \'English\',\n          last_updated: 12345678911111,\n          community_owned: false,\n          status: \'public\'\n        }, {\n          id: \'6\',\n          title: \'My Exploration\',\n          category: \'Personal\',\n          objective: \'can be for myself\',\n          language: \'English\',\n          last_updated: 12345678954322,\n          community_owned: false,\n          status: \'public\'\n        }],\n        preferred_language_codes: [\'en\']\n      });\n\n      GLOBALS.LANGUAGE_CODES_AND_NAMES = [{\n        code: \'en\',\n        name: \'English\'\n      }, {\n        code: \'es\',\n        name: \'espa\xf1ol\'\n      }, {\n        code: \'hr\',\n        name: \'hrvatski\'\n      }];\n      scope = $rootScope.$new();\n      rootScope = $rootScope;\n      ctrl = $controller(\'Library\', {\n        $scope: scope,\n        AlertsService: null,\n        DateTimeFormatService: null\n      });\n    }));\n\n    it(\'should show correct explorations\', function() {\n      // TODO(sll): Write tests for the library pages.\n    });\n  });\n});'

blocks = {}
debug_info = ''