from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/exploration_editor/editor_tab/training_answer_modal_directive.html'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'<div class="form-inline" style="margin-bottom: 10px;">\n  <div style="margin-top: 10px;">\n    <span><strong>If Oppia encounters the answer:</strong></span>\n  </div>\n\n  <div>\n    <div angular-html-bind="answerTemplate">\n    </div>\n  </div>\n\n  <br>\n\n  <div>\n    <span><strong>it will reply with:</strong></span>\n  </div>\n\n  <div>\n    <div angular-html-bind="answerFeedback">\n    </div>\n  </div>\n\n  <br>\n\n  <div>\n    <span><strong>and then direct the learner to: </strong></span>\n    <span angular-html-bind="answerOutcomeDest"></span>\n  </div>\n\n  <br>\n\n  <div>\n    <span><strong>Is this right?</strong></span>\n  </div>\n\n  <div>\n    <button class="btn btn-default" ng-disabled="changingAnswerGroupIndex" ng-click="beginChangingAnswerGroupIndex()">No</button>\n    <button class="btn btn-default" ng-disabled="changingAnswerGroupIndex" ng-click="confirmAnswerGroupIndex(classification.answerGroupIndex)">Yes</button>\n  </div>\n\n  <br>\n\n  <div ng-if="changingAnswerGroupIndex">\n    <span><strong>Select correct feedback or type a new response:</strong></span>\n\n    <div class="trained-feedback-selection-form-container">\n      <form>\n        <div class="trained-feedback-selection-container" ng-repeat="outcome in allOutcomes track by $index">\n          <button class="trained-feedback-selection" ng-click="confirmAnswerGroupIndex($index)">\n            <span ng-if="outcome.feedback.length > 0" angular-html-bind="outcome.feedback.getHtml()">\n            </span>\n            <span ng-if="outcome.feedback.length == 0">\n              <em>(No feedback)</em>\n            </span>\n\n            <br>\n\n            <span style="float: right;" ng-if="outcome.dest != getCurrentStateName()">\n              \u2192 <[outcome.dest]>\n            </span>\n            <span style="float: right;" ng-if="outcome.dest == getCurrentStateName()">\n              <em>\u2192 (try again)</em>\n            </span>\n          </button>\n        </div>\n      </form>\n    </div>\n\n    <button class="btn btn-default" ng-if="!addingNewResponse" ng-click="beginAddingNewResponse()">New Response</button>\n    <outcome-feedback-editor ng-if="addingNewResponse" outcome="classification.newOutcome">\n    </outcome-feedback-editor>\n    <button class="btn btn-default btn-success" ng-if="addingNewResponse" ng-click="confirmNewFeedback()">Save New Response</button>\n  </div>\n</div>'

blocks = {}
debug_info = ''