from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/exploration_editor/EditorNavbarBreadcrumbDirective.js'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'// Copyright 2016 The Oppia Authors. All Rights Reserved.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an "AS-IS" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\n/**\n * @fileoverview Directive for showing Editor Navbar breadcrumb\n * in editor navbar.\n */\n\noppia.directive(\'editorNavbarBreadcrumb\', [\n  \'UrlInterpolationService\', function(UrlInterpolationService) {\n    return {\n      restrict: \'E\',\n      templateUrl: UrlInterpolationService.getDirectiveTemplateUrl(\n        \'/pages/exploration_editor/\' +\n        \'editor_navbar_breadcrumb_directive.html\'),\n      controller: [\n        \'$scope\', \'ExplorationTitleService\', \'RouterService\',\n        \'FocusManagerService\', \'EXPLORATION_TITLE_INPUT_FOCUS_LABEL\',\n        function(\n            $scope, ExplorationTitleService, RouterService,\n            FocusManagerService, EXPLORATION_TITLE_INPUT_FOCUS_LABEL) {\n          $scope.navbarTitle = null;\n          $scope.$on(\'explorationPropertyChanged\', function() {\n            var _MAX_TITLE_LENGTH = 20;\n            $scope.navbarTitle = ExplorationTitleService.savedMemento;\n            if ($scope.navbarTitle.length > _MAX_TITLE_LENGTH) {\n              $scope.navbarTitle = (\n                $scope.navbarTitle.substring(0, _MAX_TITLE_LENGTH - 3) + \'...\');\n            }\n          });\n\n          $scope.editTitle = function() {\n            RouterService.navigateToSettingsTab();\n            FocusManagerService.setFocus(EXPLORATION_TITLE_INPUT_FOCUS_LABEL);\n          };\n\n          var _TAB_NAMES_TO_HUMAN_READABLE_NAMES = {\n            main: \'Edit\',\n            translation: \'Translation\',\n            preview: \'Preview\',\n            settings: \'Settings\',\n            stats: \'Statistics\',\n            history: \'History\',\n            feedback: \'Feedback\'\n          };\n\n          $scope.getCurrentTabName = function() {\n            if (!RouterService.getTabStatuses()) {\n              return \'\';\n            } else {\n              return _TAB_NAMES_TO_HUMAN_READABLE_NAMES[\n                RouterService.getTabStatuses().active];\n            }\n          };\n        }\n      ]\n    };\n  }]);'

blocks = {}
debug_info = ''