from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/exploration_editor/history_tab/HistoryTabSpec.js'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'// Copyright 2014 The Oppia Authors. All Rights Reserved.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an "AS-IS" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\n/**\n * @fileoverview Unit tests for the exploration history tab.\n */\n\ndescribe(\'HistoryTab controller\', function() {\n  beforeEach(module(\'oppia\'));\n\n  describe(\'HistoryTab\', function() {\n    var $scope, historyTabCtrl;\n\n    beforeEach(inject(function($controller, $rootScope) {\n      $scope = $rootScope.$new();\n      historyTabCtrl = $controller(\'HistoryTab\', {$scope: $scope});\n    }));\n\n    it(\'should get version numbers of revisions to be displayed\',\n      function() {\n        $scope.displayedCurrentPageNumber = 1;\n        $scope.versionCheckboxArray = [\n          {vnum: 32, selected: false},\n          {vnum: 31, selected: true},\n          {vnum: 30, selected: false},\n          {vnum: 29, selected: false},\n          {vnum: 28, selected: false},\n          {vnum: 27, selected: false},\n          {vnum: 26, selected: false},\n          {vnum: 25, selected: false},\n          {vnum: 24, selected: false},\n          {vnum: 23, selected: false},\n          {vnum: 22, selected: false},\n          {vnum: 21, selected: false},\n          {vnum: 20, selected: false},\n          {vnum: 19, selected: false},\n          {vnum: 18, selected: false},\n          {vnum: 17, selected: false},\n          {vnum: 16, selected: false},\n          {vnum: 15, selected: false},\n          {vnum: 14, selected: true},\n          {vnum: 13, selected: false},\n          {vnum: 12, selected: false},\n          {vnum: 11, selected: false},\n          {vnum: 10, selected: false},\n          {vnum: 9, selected: false},\n          {vnum: 8, selected: false},\n          {vnum: 7, selected: false},\n          {vnum: 6, selected: false},\n          {vnum: 5, selected: false},\n          {vnum: 4, selected: false},\n          {vnum: 3, selected: false},\n          {vnum: 2, selected: false},\n          {vnum: 1, selected: false}\n        ];\n        $scope.computeVersionsToDisplay();\n        expect($scope.versionNumbersToDisplay).toEqual([\n          32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,\n          15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3]);\n        $scope.displayedCurrentPageNumber = 2;\n        $scope.computeVersionsToDisplay();\n        expect($scope.versionNumbersToDisplay).toEqual([2, 1]);\n      }\n    );\n  });\n});'

blocks = {}
debug_info = ''