from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/exploration_editor/editor_tab/AnswerGroupsCacheServiceSpec.js'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'// Copyright 2018 The Oppia Authors. All Rights Reserved.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an "AS-IS" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\n/**\n * @fileoverview Unit tests for Answer Groups Cache Service.\n */\ndescribe(\'Answer Groups Cache Service\', function() {\n  describe(\'AnswerGroupsCache\', function() {\n    beforeEach(function() {\n      module(\'oppia\');\n    });\n\n\n    var answerGroup = {\n      rule_specs: [],\n      outcome: {\n        dest: \'default\',\n        feedback: {\n          content_id: \'feedback_1\',\n          html: \'\'\n        },\n        labelled_as_correct: false,\n        param_changes: [],\n        refresher_exploration_id: null\n      }\n    };\n\n    var scope, agcs;\n    beforeEach(inject(function($injector, $rootScope) {\n      scope = $rootScope.$new();\n      agcs = $injector.get(\'AnswerGroupsCacheService\');\n    }));\n\n    it(\'sets a value in the cache\', function() {\n      agcs.set(\'InteractionId\', answerGroup);\n      expect(agcs.contains(\'InteractionId\')).toBe(true);\n    });\n\n    it(\'returns null when value isnt available in the cache\', function() {\n      expect(agcs.get(\'NonPresentInteractionId\')).toEqual(null);\n    });\n\n    it(\'gets a value from the cache\', function() {\n      agcs.set(\'InteractionId\', answerGroup);\n      expect(agcs.get(\'InteractionId\')).toEqual(answerGroup);\n    });\n\n    it(\'successfully checks if the value is available in cache\', function() {\n      agcs.set(\'InteractionId\', answerGroup);\n      expect(agcs.contains(\'InteractionId\')).toBe(true);\n      expect(agcs.contains(\'NonPresentInteractionId\')).toBe(false);\n      expect(agcs.contains(\'\')).toBe(false);\n      expect(agcs.contains(1)).toBe(false);\n    });\n\n    it(\'resets the cache\', function() {\n      agcs.set(\'InteractionId\', answerGroup);\n      expect(agcs.contains(\'InteractionId\')).toBe(true);\n      agcs.reset();\n      expect(agcs.contains(\'InteractionId\')).toBe(false);\n    });\n  });\n});'

blocks = {}
debug_info = ''