from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/exploration_player/input_response_pair_directive.html'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'<div class="conversation-skin-learner-answer-container">\n  <img class="conversation-skin-user-avatar img-circle" ng-src="<[profilePicture()]>" alt="">\n  <div ng-if="!data.isHint">\n    <div ng-if="getShortAnswerHtml()"\n         popover-placement="bottom" uib-popover-template="\'popover/answer\'"\n         popover-trigger="click" style="cursor: pointer;">\n      <angular-html-bind class="rte-viewer conversation-skin-learner-answer-content" html-data="getShortAnswerHtml()">\n      </angular-html-bind>\n    </div>\n    <div ng-if="!getShortAnswerHtml()">\n      <angular-html-bind class="rte-viewer conversation-skin-learner-answer-content" html-data="getAnswerHtml()">\n      </angular-html-bind>\n    </div>\n  </div>\n  <div ng-if="data.isHint">\n    <div class="rte-viewer conversation-skin-learner-answer-content">\n      <[data.learnerInput | translate]>\n    </div>\n  </div>\n</div>\n\n<div class="conversation-skin-oppia-feedback-container" ng-if="data.oppiaResponse !== \'\'">\n  <img class="conversation-skin-oppia-avatar img-circle" ng-src="<[oppiaAvatarImageUrl()]>" alt="">\n  <div ng-if="!data.oppiaResponse && isCurrentCardAtEndOfTranscript()" class="protractor-test-input-response-loading-dots">\n    <div class="conversation-skin-feedback-dot-one"></div>\n    <div class="conversation-skin-feedback-dot-two"></div>\n    <div class="conversation-skin-feedback-dot-three"></div>\n  </div>\n  <span id="<[getInputResponsePairId()]>"></span>\n  <div>\n    <angular-html-bind ng-if="data.oppiaResponse !== null"\n                       html-data="data.oppiaResponse"\n                       class="rte-viewer conversation-skin-oppia-feedback-content protractor-test-conversation-feedback"\n                       ng-class="getFeedbackAudioHighlightClass()">\n    </angular-html-bind>\n  </div>\n</div>\n\n<style>\n  .conversation-skin-learner-answer-container,\n  .conversation-skin-oppia-feedback-container {\n    position: relative;\n    padding: 0 20px;\n  }\n\n  .conversation-skin-learner-answer-container {\n    text-align: right;\n  }\n\n  .conversation-skin-learner-answer-container .conversation-skin-user-avatar {\n    border: 2px solid #094142;\n    height: 100px;\n    right: -98px;\n    top: -33px;\n    width: 100px;\n  }\n\n  .conversation-skin-learner-answer-container:after {\n    border: 7px solid;\n    border-color: rgb(236, 239, 241) transparent transparent rgb(236, 239, 241);\n    content: \' \';\n    height: 0;\n    position: absolute;\n    top: 11%;\n    width: 0;\n  }\n\n  .conversation-skin-tutor-card-middle-section .conversation-skin-learner-answer-container:after {\n    border-color: rgba(236, 239, 241, 0.4) transparent transparent rgba(236, 239, 241, 0.4);\n  }\n</style>\n\n<script type="text/ng-template" id="popover/answer">\n  <div>\n    <angular-html-bind html-data="answer()">\n    </angular-html-bind>\n  </div>\n</script>'

blocks = {}
debug_info = ''