from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'components/share/SharingLinksDirective.js'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'// Copyright 2016 The Oppia Authors. All Rights Reserved.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an "AS-IS" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\n/**\n * @fileoverview Directive for the Social Sharing Links.\n */\n\noppia.directive(\'sharingLinks\', [\n  \'UrlInterpolationService\', function(UrlInterpolationService) {\n    return {\n      restrict: \'E\',\n      scope: {\n        layoutType: \'@\',\n        layoutAlignType: \'@\',\n        shareType: \'@\',\n        getTwitterText: \'&twitterText\',\n        getExplorationId: \'&explorationId\',\n        getCollectionId: \'&collectionId\'\n      },\n      templateUrl: UrlInterpolationService.getDirectiveTemplateUrl(\n        \'/components/share/\' +\n        \'sharing_links_directive.html\'),\n      controller: [\n        \'$scope\', \'$window\', \'HtmlEscaperService\',\n        \'ExplorationEmbedButtonService\', \'siteAnalyticsService\',\n        function(\n            $scope, $window, HtmlEscaperService,\n            ExplorationEmbedButtonService, siteAnalyticsService) {\n          $scope.registerShareEvent = null;\n\n          if ($scope.shareType === \'exploration\') {\n            $scope.explorationId = $scope.getExplorationId();\n\n            $scope.activityType = \'explore\';\n            $scope.activityId = $scope.explorationId;\n\n            $scope.registerShareEvent = (\n              siteAnalyticsService.registerShareExplorationEvent);\n\n            $scope.showEmbedExplorationModal = (\n              ExplorationEmbedButtonService.showModal);\n          } else if ($scope.shareType === \'collection\') {\n            $scope.collectionId = $scope.getCollectionId();\n\n            $scope.activityType = \'collection\';\n            $scope.activityId = $scope.collectionId;\n\n            $scope.registerShareEvent = (\n              siteAnalyticsService.registerShareCollectionEvent);\n          } else {\n            throw Error(\n              \'SharingLinks directive can only be used either in the\' +\n              \'collection player or the exploration player\');\n          }\n\n          $scope.serverName = (\n            $window.location.protocol + \'//\' + $window.location.host);\n\n          $scope.escapedTwitterText = (\n            HtmlEscaperService.unescapedStrToEscapedStr(\n              $scope.getTwitterText()));\n\n          $scope.classroomUrl = UrlInterpolationService.getStaticImageUrl(\n            \'/general/classroom.png\');\n        }\n      ]\n    };\n  }]);'

blocks = {}
debug_info = ''