from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/state_editor/state_editor_directive.html'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'<md-card class="oppia-editor-card-with-avatar">\n  <div class="oppia-editor-card-body">\n    <img ng-src="<[oppiaBlackImgUrl]>" alt="" class="oppia-editor-card-avatar">\n    <div id="tutorialStateContent" class="oppia-editor-card-section"\n         style="padding-top: 36px; padding-bottom: 36px;">\n      <state-content-editor on-save-state-content="onSaveStateContent"\n                            on-save-content-ids-to-audio-translations="onSaveContentIdsToAudioTranslations"\n                            state-content-placeholder="getStateContentPlaceholder()">\n      </state-content-editor>\n    </div>\n  </div>\n</md-card>\n\n<div ng-show="isInteractionShown()">\n  <state-interaction-editor on-save-state-content="onSaveStateContent"\n                            on-save-interaction-id="onSaveInteractionId"\n                            on-save-interaction-customization-args="onSaveInteractionCustomizationArgs"\n                            on-save-solution="onSaveSolution"\n                            on-save-content-ids-to-audio-translations="onSaveContentIdsToAudioTranslations"\n                            recompute-graph="recomputeGraph">\n  </state-interaction-editor>\n</div>\n\n<div ng-hide="!interactionIdIsSet || currentStateIsTerminal">\n  <state-responses on-save-content-ids-to-audio-translations="onSaveContentIdsToAudioTranslations"\n                   on-save-interaction-default-outcome="onSaveInteractionDefaultOutcome"\n                   on-save-interaction-answer-groups="onSaveInteractionAnswerGroups"\n                   navigate-to-state="navigateToState"\n                   add-state="addState"\n                   refresh-warnings="refreshWarnings"\n                   on-responses-initialized="reinitializeEditor">\n  </state-responses>\n  <div>\n    <state-hints-editor on-save-hints="onSaveHints"\n                        on-save-solution="onSaveSolution"\n                        on-save-content-ids-to-audio-translations="onSaveContentIdsToAudioTranslations">\n    </state-hints-editor>\n  </div>\n  <div ng-if="currentInteractionCanHaveSolution">\n    <state-solution-editor on-save-solution="onSaveSolution"\n                           on-save-content-ids-to-audio-translations="onSaveContentIdsToAudioTranslations"\n                           refresh-warnings="refreshWarnings">\n    </state-solution-editor>\n  </div>\n</div>'

blocks = {}
debug_info = ''