from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'pages/collection_editor/CollectionEditorNavbarBreadcrumbDirective.js'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'// Copyright 2016 The Oppia Authors. All Rights Reserved.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an "AS-IS" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\n/**\n * @fileoverview Controller for the navbar breadcrumb of the collection editor.\n */\n\n// TODO(bhenning): After the navbar is moved to a directive, this directive\n// should be updated to say \'Loading...\' if the collection editor\'s controller\n// is not yet finished loading the collection. Also, this directive should\n// support both displaying the current title of the collection (or untitled if\n// it does not yet have one) or setting a new title in the case of an untitled\n// collection.\noppia.directive(\'collectionEditorNavbarBreadcrumb\', [\n  \'UrlInterpolationService\', function(UrlInterpolationService) {\n    return {\n      restrict: \'E\',\n      scope: {},\n      templateUrl: UrlInterpolationService.getDirectiveTemplateUrl(\n        \'/pages/collection_editor/\' +\n        \'collection_editor_navbar_breadcrumb_directive.html\'),\n      controller: [\n        \'$scope\', \'RouterService\', \'CollectionEditorStateService\',\n        \'FocusManagerService\', \'COLLECTION_TITLE_INPUT_FOCUS_LABEL\',\n        function(\n            $scope, RouterService, CollectionEditorStateService,\n            FocusManagerService, COLLECTION_TITLE_INPUT_FOCUS_LABEL) {\n          var _TAB_NAMES_TO_HUMAN_READABLE_NAMES = {\n            main: \'Edit\',\n            preview: \'Preview\',\n            settings: \'Settings\',\n            stats: \'Statistics\',\n            history: \'History\'\n          };\n\n          $scope.collection = CollectionEditorStateService.getCollection();\n\n          $scope.getCurrentTabName = function() {\n            return _TAB_NAMES_TO_HUMAN_READABLE_NAMES[\n              RouterService.getTabStatuses().active];\n          };\n\n          $scope.editCollectionTitle = function() {\n            RouterService.navigateToSettingsTab();\n            FocusManagerService.setFocus(COLLECTION_TITLE_INPUT_FOCUS_LABEL);\n          };\n        }\n      ]\n    };\n  }]);'

blocks = {}
debug_info = ''