from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace
name = 'domain/sidebar/SidebarStatusServiceSpec.js'

def root(context, missing=missing):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    if 0: yield None
    pass
    yield u'// Copyright 2018 The Oppia Authors. All Rights Reserved.\n//\n// Licensed under the Apache License, Version 2.0 (the "License");\n// you may not use this file except in compliance with the License.\n// You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n// Unless required by applicable law or agreed to in writing, software\n// distributed under the License is distributed on an "AS-IS" BASIS,\n// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n// See the License for the specific language governing permissions and\n// limitations under the License.\n\n/**\n * @fileoverview Tests for SidebarStatusService.\n */\n\ndescribe(\'SidebarStatusService\', function() {\n  var SidebarStatusService;\n\n  beforeEach(module(\'oppia\'));\n  beforeEach(inject(function($injector, _$window_) {\n    $window = _$window_;\n    $window.innerWidth = 600;\n    SidebarStatusService = $injector.get(\'SidebarStatusService\');\n  }));\n\n  it(\'should open the sidebar if its not open\', function() {\n    SidebarStatusService.openSidebar();\n    expect(SidebarStatusService.isSidebarShown()).toBe(true);\n  });\n\n  it(\'should close the sidebar when its open\', function() {\n    SidebarStatusService.openSidebar();\n    SidebarStatusService.closeSidebar();\n    expect(SidebarStatusService.isSidebarShown()).toBe(false);\n  });\n\n  it(\'should toggle the sidebar to open and then close\', function(){\n    SidebarStatusService.toggleSidebar();\n    expect(SidebarStatusService.isSidebarShown()).toBe(true);\n    SidebarStatusService.toggleSidebar();\n    expect(SidebarStatusService.isSidebarShown()).toBe(false);\n  });\n\n\n  it(\'should falsify pendingSidebarClick on document click\', function(){\n    SidebarStatusService.openSidebar();\n    SidebarStatusService.onDocumentClick();\n    expect(SidebarStatusService.isSidebarShown()).toBe(true);\n    SidebarStatusService.onDocumentClick();\n    expect(SidebarStatusService.isSidebarShown()).toBe(false);\n  });\n});'

blocks = {}
debug_info = ''